services:
  timeseriesprocessing.api:
    container_name: api
    image: timeseriesprocessing.api
    build:
      context: .
      dockerfile: TimeSeriesProcessing.Api/Dockerfile
    environment:
      ASPNETCORE_ENVIRONMENT: Production

  timeseriesprocessing.db:
    container_name: db
    image: postgres:16
    restart: unless-stopped
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5433:5432"